### ISSUE TITLE
2.0.1 composer breaks simple-mysqli

### ISSUE THREAD

**Issue by igloocube** [voku/simple-cache#10]
This is fixed in master but it isn't pushed as a release so it has broken simple-mysqli suddenly.

```
"autoload": {
    "psr-0": {
        "voku": "src"
    }
}
```

Needs to be:

```
"autoload": {
    "psr-0": {
        "voku\\cache\\": "src"
    }
}
```

**Comment by voku** [comment]
thx for report! The problem should already fixed with https://github.com/voku/simple-cache/commit/551795af784d9aed00d6b0c523486e2d28922d78 + I have added a new git tag

**Comment by igloocube** [comment]
@voku Thanks! BTW, same thing effects portable-utf8 - want me to open a new issue there is mentioning here ok?

**Comment by voku** [comment]
Oki! The problem should already fixed with https://github.com/voku/portable-utf8/commit/267b5667513c56846a339f23f960fee867ad18d5 + git tag is alredy done ...
