### ISSUE TITLE
opcache function call will cause warnings in hosting environments

### ISSUE THREAD

**Issue by hannob** [voku/simple-cache#19]
For security reasons it's common to restrict the opcache API in shared webhosting environments.

This is usually no problem, because applications have little reason to call into the opcache api directly. But in your library (which recently got added as a dependency to the serendipity blog software) this is the case, and it will cause warnings like:
```
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in [path]/bundled-libs/voku/simple-cache/src/voku/cache/AdapterOpCache.php:32
```

See here for a similar issue in wp super cache:
https://github.com/Automattic/wp-super-cache/issues/536

One workaround would be to prefix the \opcache_get_status() with @ to avoid the warning, i.e. change the code to:
```
            self::$hasCompileFileFunction = \function_exists('opcache_compile_file') && !empty(@Bilge @\opcache_get_status());
```

**Comment by voku** [comment]
Thanks for the good bug report. :+1: Fixed in version 4.0.1.
